#!/usr/bin/env python
# license removed for brevity
import rospy
from dynamic_graph_bridge_msgs.msg import Vector
from sensor_msgs.msg import JointState

rospy.init_node('sot_reemitter', anonymous=True)
pub = rospy.Publisher('/sot/joint_state', JointState, queue_size=10)
    
seqnb = 0
aJS = JointState()

jointnames =  [
'leg_left_1_joint', 'leg_left_2_joint', 'leg_left_3_joint', 'leg_left_4_joint', 'leg_left_5_joint', 'leg_left_6_joint',
'leg_right_1_joint', 'leg_right_2_joint', 'leg_right_3_joint', 'leg_right_4_joint', 'leg_right_5_joint', 'leg_right_6_joint',
'torso_1_joint', 'torso_2_joint',
'arm_left_1_joint', 'arm_left_2_joint', 'arm_left_3_joint', 'arm_left_4_joint', 'arm_left_5_joint', 'arm_left_6_joint', 'arm_left_7_joint', 'gripper_left_joint','arm_right_1_joint', 'arm_right_2_joint', 'arm_right_3_joint', 'arm_right_4_joint', 'arm_right_5_joint', 'arm_right_6_joint', 'arm_right_7_joint',  'gripper_right_joint',
'head_1_joint', 'head_2_joint',
]
    
def jointreceived(jstates):
    global seqnb
    seqnb = seqnb+1
    aJS.header.seq = seqnb
    aJS.header.stamp = rospy.Time.now()
    aJS.header.frame_id = "base_link"
    aJS.name = jointnames
    aJS.position = jstates.data[6:]
    aJS.velocity = []
    aJS.effort = []
    pub.publish(aJS)

def listener():
    rospy.Subscriber("/sot_hpp/state", Vector, jointreceived)
    rospy.spin()
    
if __name__ == '__main__':
    try:
        listener()
    except rospy.ROSInterruptException:
        pass
